version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./init.sh:/init.sh

        ports:
            - "9001:9000"
        command:
            - /bin/bash
            - -c
            - |
                chmod +x /init.sh && /init.sh && php-fpm
        depends_on:
            - db

    webserver:
        image: nginx
        container_name: webserver
        ports:
            - "8000:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app

    db:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        volumes:
            - dbdata:/var/lib/mysql/

volumes:
    dbdata:
        driver: local
